import Head from 'next/head'

export default function Blog() {
  return (
    <>
      <Head>
        <title>F. Veronezi — Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex w-full max-w-screen-sm">
        <h1 className="text-4xl font-bold">Blog</h1>
      </main>
    </>
  )
}
