import Head from 'next/head'

export default function Blog() {
  return (
    <>
      <Head>
        <title>F. Veronezi — Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex w-full max-w-screen-sm flex-col gap-5 px-6 lg:px-0">
        <h1 className="text-4xl font-bold">Blog</h1>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima, at? Enim minus, aliquam autem nostrum in
          minima doloremque ad nobis nesciunt aut assumenda quibusdam! Hic incidunt alias asperiores aperiam cupiditate.
        </p>
      </main>
    </>
  )
}
