import { Cards } from '@/components/Cards'
import { Heading } from '@/components/Heading'
import { Introduction } from '@/components/Introduction'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>F. Veronezi — Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex h-full w-full max-w-screen-sm flex-col gap-5 px-6 lg:px-0">
        <Heading />
        <Introduction />
        <Cards />
      </main>
    </>
  )
}
